services:

    #
    # Resize
    #
    fomalhaut.media_resize_adapter.imagemagick:
        class: Fomalhaut\Component\Media\Adapter\Resizer\ImageMagickResizeAdapter
        arguments:
            - %fomalhaut.image_resize_converter_bin_path%
            - %fomalhaut.image_resize_converter_default_profile%

    fomalhaut.media_resize_adapter.gd:
        class: Fomalhaut\Component\Media\Adapter\Resizer\GDResizeAdapter
