services:

    #
    # Event Dispatchers
    #
    fomalhaut.event_dispatcher.media:
        class: Fomalhaut\Component\Media\EventDispatcher\MediaEventDispatcher
        parent: elcodi.event_dispatcher.abstract
