services:

    #
    # Factories
    #

    #
    # Factory for entity image
    #
    fomalhaut.factory.image:
        class: Fomalhaut\Component\Media\Factory\ImageFactory
        calls:
            - [setEntityNamespace, ["%fomalhaut.entity.image.class%"]]
            - [setDateTimeFactory, ["@elcodi.factory.datetime"]]
