services:

    #
    # Service
    #
    fomalhaut.manager.media_file:
        class: Fomalhaut\Component\Media\Services\FileManager
        arguments:
            - '@fomalhaut.media_filesystem'
            - '@fomalhaut.transformer.media_file_identifier'

    fomalhaut.manager.media_image:
        class: Fomalhaut\Component\Media\Services\ImageManager
        arguments:
            - '@fomalhaut.factory.image'
            - '@fomalhaut.manager.media_file'
            - '@fomalhaut.media_resize_adapter'

    fomalhaut.uploader.image:
        class: Fomalhaut\Component\Media\Services\ImageUploader
        arguments:
            - '@fomalhaut.object_manager.image'
            - '@fomalhaut.manager.media_file'
            - '@fomalhaut.manager.media_image'
            - '@fomalhaut.event_dispatcher.media'            