services:

    #
    # Service
    #
    fomalhaut.manager.media_file:
        class: Fomalhaut\Component\Media\Services\FileManager
        arguments:
            - '@fomalhaut.media_filesystem'
            - '@fomalhaut.transformer.media_file_identifier'