Fomalhaut\Component\User\Entity\Abstracts\AbstractUser:
    type: mappedSuperclass
    fields:
        username:
            column: username
            type: string
            length: 255
            nullable: true
        password:
            column: password
            type: string
            length: 255
            nullable: true
        email:
            column: email
            type: string
            length: 255
            nullable: true
        phone:
            column: phone
            type: string
            length: 15
            nullable: true
        firstname:
            column: firstname
            type: string
            length: 255
            nullable: true
        lastname:
            column: lastname
            type: string
            length: 255
            nullable: true