services:

    #
    # Provider user factories
    #
    fomalhaut.user_provider_entity_instance:
        class: %fomalhaut.entity.user.class%
        factory:
            - '@fomalhaut.factory.user'
            - create

    #
    # Providers
    #
    fomalhaut.provider.user_provider:
        class: Symfony\Component\Security\Core\Encoder\PasswordEncoderInterface
        factory:
            - '@security.encoder_factory'
            - getEncoder
        arguments:
            - '@fomalhaut.user_provider_entity_instance'