services:
    #
    # Services
    #
    fomalhaut.manager.password:
        class: Fomalhaut\Component\User\Services\PasswordManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@router'
            - '@fomalhaut.event_dispatcher.password'
            - '@elcodi.generator.sha1'
